global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["192.168.6.14:8000"]

  - job_name: "docker"
    static_configs:
      - targets: ["192.168.6.14:9323"]

rule_files:
  - /etc/prometheus/alert.rules  # Reference to the alert rules file
